/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javaapplication1.DSKhachHang;

/**
 *
 * @author Lenovo
 */
public class adminview extends javax.swing.JFrame {

    /**
     * Creates new form adminview
     */
    public adminview() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jSplitPane1.setEnabled(false);
        jSplitPane1.setDividerSize(1);
        jPanel1 = new javax.swing.JPanel();
        jbuttondanhsach = new javax.swing.JButton();
        jbuttonthongke = new javax.swing.JButton();
        jbuttonQLSanpham = new javax.swing.JButton();
        jbuttonKhuyenmai = new javax.swing.JButton();
        jbuttonQLNhanvien = new javax.swing.JButton();
        jbuttonBanhang = new javax.swing.JButton();
        jbuttonDoiHang = new javax.swing.JButton();
        jbuttonDangXuat = new javax.swing.JButton();
        jbuttonKhachHang = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(34, 47, 62));
        jPanel1.setForeground(new java.awt.Color(242, 242, 242));

        jbuttondanhsach.setText("Danh sách");

        jbuttonthongke.setText("Thống kê");
        jbuttonthongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonthongkeActionPerformed(evt);
            }
        });

        jbuttonQLSanpham.setText("QL Sản phẩm");
        jbuttonQLSanpham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonQLSanphamActionPerformed(evt);
            }
        });

        jbuttonKhuyenmai.setText("Khuyến mãi");
        jbuttonKhuyenmai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonKhuyenmaiActionPerformed(evt);
            }
        });

        jbuttonQLNhanvien.setText("QL Nhân viên");
        jbuttonQLNhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonQLNhanvienActionPerformed(evt);
            }
        });

        jbuttonBanhang.setText("Bán hàng");
        jbuttonBanhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonBanhangActionPerformed(evt);
            }
        });

        jbuttonDoiHang.setText("Đổi hàng");
        jbuttonDoiHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonDoiHangActionPerformed(evt);
            }
        });

        jbuttonDangXuat.setText("Đăng xuất");
        jbuttonDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonDangXuatActionPerformed(evt);
            }
        });

        jbuttonKhachHang.setText("Khách Hàng");
        jbuttonKhachHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonKhachHangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbuttonBanhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jbuttonDangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbuttonQLNhanvien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbuttonQLSanpham, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbuttonthongke, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbuttonKhuyenmai, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbuttondanhsach, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jbuttonDoiHang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbuttonKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jbuttondanhsach, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jbuttonthongke, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jbuttonQLSanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jbuttonBanhang)
                .addGap(34, 34, 34)
                .addComponent(jbuttonQLNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jbuttonKhuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jbuttonDoiHang)
                .addGap(31, 31, 31)
                .addComponent(jbuttonKhachHang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                .addComponent(jbuttonDangXuat)
                .addGap(38, 38, 38))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jLabel1.setBackground(new java.awt.Color(34, 47, 62));
        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ứng dụng quản lý và bán hàng ");
        jLabel1.setBorder(new javax.swing.border.MatteBorder(null));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/banner.png"))); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(362, 362, 362)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(408, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSplitPane1.setRightComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1464, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonDangXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbuttonDangXuatActionPerformed

    private void jbuttonDoiHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonDoiHangActionPerformed
        // TODO add your handling code here:
        DoiHang doihangjpanel = new DoiHang(); // JPanel bạn đã tạo sẵn
        jSplitPane1.setRightComponent(doihangjpanel); // Gắn vào bên phải của JSplitPane
    }//GEN-LAST:event_jbuttonDoiHangActionPerformed

    private void jbuttonBanhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonBanhangActionPerformed
        // TODO add your handling code here:
        BanHangView banhangjpanel = new BanHangView(); // JPanel bạn đã tạo sẵn
        jSplitPane1.setRightComponent(banhangjpanel); // Gắn vào bên phải của JSplitPane
    }//GEN-LAST:event_jbuttonBanhangActionPerformed

    private void jbuttonQLNhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonQLNhanvienActionPerformed
        QuanLyNhanvien qlNhanVienPanel = new QuanLyNhanvien(); // JPanel bạn đã tạo sẵn
        jSplitPane1.setRightComponent(qlNhanVienPanel); // Gắn vào bên phải của JSplitPane

    }//GEN-LAST:event_jbuttonQLNhanvienActionPerformed

    private void jbuttonKhuyenmaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonKhuyenmaiActionPerformed
        // TODO add your handling code here:
        KhuyenMai khuyenmaiPanel = new KhuyenMai(); // JPanel bạn đã tạo sẵn
        jSplitPane1.setRightComponent(khuyenmaiPanel); // Gắn vào bên phải của JSplitPane
    }//GEN-LAST:event_jbuttonKhuyenmaiActionPerformed

    private void jbuttonQLSanphamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonQLSanphamActionPerformed
        // TODO add your handling code here:
        QuanLySanPham qlsanphamPanel = new QuanLySanPham(); // JPanel bạn đã tạo sẵn
        jSplitPane1.setRightComponent(qlsanphamPanel); // Gắn vào bên phải của JSplitPane
    }//GEN-LAST:event_jbuttonQLSanphamActionPerformed

    private void jbuttonthongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonthongkeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbuttonthongkeActionPerformed

    private void jbuttonKhachHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonKhachHangActionPerformed
        // TODO add your handling code here:
        DSKhachHang DSkhachHangPanel = new DSKhachHang(); // JPanel bạn đã tạo sẵn
        jSplitPane1.setRightComponent(DSkhachHangPanel); // Gắn vào bên phải của JSplitPane
    }//GEN-LAST:event_jbuttonKhachHangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JButton jbuttonBanhang;
    private javax.swing.JButton jbuttonDangXuat;
    private javax.swing.JButton jbuttonDoiHang;
    private javax.swing.JButton jbuttonKhachHang;
    private javax.swing.JButton jbuttonKhuyenmai;
    private javax.swing.JButton jbuttonQLNhanvien;
    private javax.swing.JButton jbuttonQLSanpham;
    private javax.swing.JButton jbuttondanhsach;
    private javax.swing.JButton jbuttonthongke;
    // End of variables declaration//GEN-END:variables
}
