package view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class QuanLyNhanvien extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public QuanLyNhanvien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldTim = new javax.swing.JTextField();
        jbuttonXuatExcel = new javax.swing.JButton();
        jbuttonTim = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelHoten = new javax.swing.JLabel();
        jLabelCCCD = new javax.swing.JLabel();
        jLabelNamsinh = new javax.swing.JLabel();
        jLabelGioitinh = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelSDT = new javax.swing.JLabel();
        jLabelDiaChi = new javax.swing.JLabel();
        jLabelTaikhoandn = new javax.swing.JLabel();
        jTextFieldHoTen = new javax.swing.JTextField();
        jTextFieldCCCD = new javax.swing.JTextField();
        jTextFieldSDT = new javax.swing.JTextField();
        jTextFieldDiachi = new javax.swing.JTextField();
        jTextFieldNamsinh = new javax.swing.JTextField();
        jTextFieldTaikhoandn = new javax.swing.JTextField();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabelTrangThai = new javax.swing.JLabel();
        jLabelMatkhau = new javax.swing.JLabel();
        jTextFieldMatkhaudn = new javax.swing.JTextField();
        jRadioButtonNam = new javax.swing.JRadioButton();
        jRadioButtonNu = new javax.swing.JRadioButton();
        jComboBoxtrangthai = new javax.swing.JComboBox<>();
        jbuttonLamMoi = new javax.swing.JButton();
        jbuttonThem = new javax.swing.JButton();
        jbuttonXoa = new javax.swing.JButton();
        jbuttonCapNhat = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(1214, 673));
        setMinimumSize(new java.awt.Dimension(1214, 673));

        jPanel1.setBackground(new java.awt.Color(34, 47, 62));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quản Lý Nhân Viên");

        jTextFieldTim.setText("Nhập tên nv cần tìm");
        jTextFieldTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTimActionPerformed(evt);
            }
        });

        jbuttonXuatExcel.setBackground(new java.awt.Color(34, 47, 62));
        jbuttonXuatExcel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jbuttonXuatExcel.setForeground(new java.awt.Color(255, 255, 255));
        jbuttonXuatExcel.setText("Xuất excel");
        jbuttonXuatExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonXuatExcelActionPerformed(evt);
            }
        });

        jbuttonTim.setBackground(new java.awt.Color(34, 47, 62));
        jbuttonTim.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jbuttonTim.setForeground(new java.awt.Color(255, 255, 255));
        jbuttonTim.setText("Tìm");
        jbuttonTim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonTimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldTim, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jbuttonTim, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jbuttonXuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldTim, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonXuatExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonTim, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Họ và tên", "Năm sinh", "Giới Tính", "CCCD", "SDT", "Email", "Địa chỉ", "Tài khoản ĐN", "Mật khẩu"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabelHoten.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelHoten.setText("Họ và tên");

        jLabelCCCD.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelCCCD.setText("CCCD");

        jLabelNamsinh.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelNamsinh.setText("Năm sinh");

        jLabelGioitinh.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelGioitinh.setText("Giới tính");

        jLabelEmail.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelEmail.setText("Email");

        jLabelSDT.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelSDT.setText("SDT");

        jLabelDiaChi.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelDiaChi.setText("Địa chỉ");

        jLabelTaikhoandn.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelTaikhoandn.setText("Tài khoản ĐN");

        jTextFieldHoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHoTenActionPerformed(evt);
            }
        });

        jLabelTrangThai.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelTrangThai.setText("Trạng thái");

        jLabelMatkhau.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabelMatkhau.setText("Mật Khẩu ĐN");

        jRadioButtonNam.setText("Nam");
        jRadioButtonNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNamActionPerformed(evt);
            }
        });

        jRadioButtonNu.setText("Nữ");

        jComboBoxtrangthai.setMaximumRowCount(3);
        jComboBoxtrangthai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Còn làm việc", "Đã nghĩ việc" }));
        jComboBoxtrangthai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxtrangthaiActionPerformed(evt);
            }
        });

        jbuttonLamMoi.setBackground(new java.awt.Color(34, 47, 62));
        jbuttonLamMoi.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jbuttonLamMoi.setForeground(new java.awt.Color(255, 255, 255));
        jbuttonLamMoi.setText("Làm mới");
        jbuttonLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonLamMoiActionPerformed(evt);
            }
        });

        jbuttonThem.setBackground(new java.awt.Color(34, 47, 62));
        jbuttonThem.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jbuttonThem.setForeground(new java.awt.Color(255, 255, 255));
        jbuttonThem.setText("Thêm ");
        jbuttonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonThemActionPerformed(evt);
            }
        });

        jbuttonXoa.setBackground(new java.awt.Color(34, 47, 62));
        jbuttonXoa.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jbuttonXoa.setForeground(new java.awt.Color(255, 255, 255));
        jbuttonXoa.setText("Xóa");
        jbuttonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonXoaActionPerformed(evt);
            }
        });

        jbuttonCapNhat.setBackground(new java.awt.Color(34, 47, 62));
        jbuttonCapNhat.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jbuttonCapNhat.setForeground(new java.awt.Color(255, 255, 255));
        jbuttonCapNhat.setText("Cập nhật");
        jbuttonCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonCapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTaikhoandn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTaikhoandn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(137, 137, 137)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelMatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldMatkhaudn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelNamsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldNamsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jRadioButtonNam)
                                        .addGap(18, 18, 18)
                                        .addComponent(jRadioButtonNu)))
                                .addGap(178, 178, 178))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxtrangthai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(163, 163, 163)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbuttonLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbuttonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jbuttonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbuttonCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelHoten, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelNamsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNamsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCCCD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonNam)
                            .addComponent(jRadioButtonNu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbuttonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbuttonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldDiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxtrangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTaikhoandn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldTaikhoandn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelMatkhau, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldMatkhaudn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbuttonLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbuttonCapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldHoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHoTenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldHoTenActionPerformed

    private void jRadioButtonNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonNamActionPerformed

    private void jComboBoxtrangthaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxtrangthaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxtrangthaiActionPerformed

    private void jbuttonLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonLamMoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbuttonLamMoiActionPerformed

    private void jbuttonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonThemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbuttonThemActionPerformed

    private void jbuttonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbuttonXoaActionPerformed

    private void jbuttonCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonCapNhatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbuttonCapNhatActionPerformed

    private void jTextFieldTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTimActionPerformed

    private void jbuttonXuatExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonXuatExcelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbuttonXuatExcelActionPerformed

    private void jbuttonTimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonTimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbuttonTimActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> jComboBoxtrangthai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCCCD;
    private javax.swing.JLabel jLabelDiaChi;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelGioitinh;
    private javax.swing.JLabel jLabelHoten;
    private javax.swing.JLabel jLabelMatkhau;
    private javax.swing.JLabel jLabelNamsinh;
    private javax.swing.JLabel jLabelSDT;
    private javax.swing.JLabel jLabelTaikhoandn;
    private javax.swing.JLabel jLabelTrangThai;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonNam;
    private javax.swing.JRadioButton jRadioButtonNu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCCCD;
    private javax.swing.JTextField jTextFieldDiachi;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldHoTen;
    private javax.swing.JTextField jTextFieldMatkhaudn;
    private javax.swing.JTextField jTextFieldNamsinh;
    private javax.swing.JTextField jTextFieldSDT;
    private javax.swing.JTextField jTextFieldTaikhoandn;
    private javax.swing.JTextField jTextFieldTim;
    private javax.swing.JButton jbuttonCapNhat;
    private javax.swing.JButton jbuttonLamMoi;
    private javax.swing.JButton jbuttonThem;
    private javax.swing.JButton jbuttonTim;
    private javax.swing.JButton jbuttonXoa;
    private javax.swing.JButton jbuttonXuatExcel;
    // End of variables declaration//GEN-END:variables
}
