package view;


import DataAccessObject.SanPhamModelDAO;
import controller.QuanLySanPhamController;
import java.awt.Font;
import java.awt.Image;
import java.io.File;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import model.SanPhamModel;
import view.Taosanphammoi;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class QuanLySanPham extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel1
     */
    public QuanLySanPham() {
    // 1. Bắt buộc gọi đầu tiên
    initComponents();
   
    // 2. Gán model có hỗ trợ ảnh
    DefaultTableModel model = new DefaultTableModel(
        new String[] {
            "Mã sản phẩm", "Tên sản phẩm", "Ảnh", "Loại sản phẩm", "Số lượng", "Giá bán", "Đơn vị", "Trạng thái","Tên file ảnh"
        }, 0
    ) {
        Class[] types = new Class[] {
            Integer.class, String.class, ImageIcon.class, Integer.class, Integer.class, Double.class, String.class, String.class
        };

        @Override
        public Class<?> getColumnClass(int columnIndex) {
            return types[columnIndex];
        }

        @Override
        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return false;
        }
    };

    jTable1.setModel(model);
    jTable1.setRowHeight(90); // ảnh không bị cắt

    // 3. Font hiện đại
    jTable1.setFont(new Font("Segoe UI", Font.PLAIN, 14));
    jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 15));

    // 4. Căn giữa các ô TRỪ cột Ảnh
    DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
    centerRenderer.setHorizontalAlignment(javax.swing.JLabel.CENTER);
    for (int i = 0; i < jTable1.getColumnCount(); i++) {
        if (i != 2) { // Không áp dụng cho cột ảnh
            jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }

    // 5. Gán riêng renderer cho cột ảnh
    jTable1.getColumnModel().getColumn(2).setCellRenderer(new DefaultTableCellRenderer() {
        @Override
        public void setValue(Object value) {
            if (value instanceof ImageIcon) {
                setIcon((ImageIcon) value);
                setText("");
            } else {
                super.setValue(value);
            }
        }
    });

    // 6. Set lại độ rộng 1 số cột nếu muốn
    jTable1.getColumnModel().getColumn(0).setPreferredWidth(50);   // Mã
    jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);  // Ảnh

    // 7. Gọi Controller duy nhất 1 lần
    controller = new QuanLySanPhamController(this);
   
}





    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtontaosanphammoi = new javax.swing.JButton();
        jButtonxuatexcel = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldnhaptenmasp = new javax.swing.JTextField();
        jButtontim = new javax.swing.JButton();
        jButtonHuytim = new javax.swing.JButton();
        jLabelthongbaotim = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabelmasp = new javax.swing.JLabel();
        jLabelloaisp = new javax.swing.JLabel();
        jLabeltensp = new javax.swing.JLabel();
        jLabelspluongsanpham = new javax.swing.JLabel();
        jLabeldonvisp = new javax.swing.JLabel();
        jLabelgiabansp = new javax.swing.JLabel();
        jLabeltrangthaisp = new javax.swing.JLabel();
        jTextFieldmasp = new javax.swing.JTextField();
        jTextFieldtensp = new javax.swing.JTextField();
        jTextFieldsoluongsp = new javax.swing.JTextField();
        jTextFielddonvisp = new javax.swing.JTextField();
        jTextFieldgiabansp = new javax.swing.JTextField();
        jTextFieldtrangthaisp = new javax.swing.JTextField();
        jLabelanh = new javax.swing.JLabel();
        jButtoncapnhap = new javax.swing.JButton();
        jButtonlammoi = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setMaximumSize(null);
        setPreferredSize(new java.awt.Dimension(1214, 673));

        jPanel1.setBackground(new java.awt.Color(34, 47, 62));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Quản lí sản phẩm");

        jButtontaosanphammoi.setText("Tạo sản phẩm mới");
        jButtontaosanphammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontaosanphammoiActionPerformed(evt);
            }
        });

        jButtonxuatexcel.setText("Xuất excel");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(507, 507, 507)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtontaosanphammoi)
                .addGap(42, 42, 42)
                .addComponent(jButtonxuatexcel)
                .addGap(60, 60, 60))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtontaosanphammoi)
                        .addComponent(jButtonxuatexcel)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setMaximumSize(new java.awt.Dimension(1214, 673));

        jTextFieldnhaptenmasp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldnhaptenmasp.setText("Nhập tên / mã sản phẩm");
        jTextFieldnhaptenmasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnhaptenmaspActionPerformed(evt);
            }
        });

        jButtontim.setBackground(new java.awt.Color(34, 47, 62));
        jButtontim.setForeground(new java.awt.Color(255, 255, 255));
        jButtontim.setText("Tìm");
        jButtontim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontimActionPerformed(evt);
            }
        });

        jButtonHuytim.setBackground(new java.awt.Color(34, 47, 62));
        jButtonHuytim.setForeground(new java.awt.Color(255, 255, 255));
        jButtonHuytim.setText("Hủy");
        jButtonHuytim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHuytimActionPerformed(evt);
            }
        });

        jLabelthongbaotim.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelthongbaotim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldnhaptenmasp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                .addGap(54, 54, 54)
                .addComponent(jButtontim)
                .addGap(40, 40, 40)
                .addComponent(jButtonHuytim)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldnhaptenmasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtontim)
                    .addComponent(jButtonHuytim))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelthongbaotim, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 589, Short.MAX_VALUE)
        );

        jTabbedPane2.setMaximumSize(new java.awt.Dimension(1214, 673));
        jTabbedPane2.setMinimumSize(new java.awt.Dimension(1214, 673));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(

            new Object [][] {},
            new String [] {
                "Mã sản phẩm", "Tên sản phẩm", "Ảnh", "Loại sản phẩm", "Số lượng", "Giá bán", "Đơn vị", "Trạng thái"
            }
        ) {
            Class[] types = new Class[] {
                Integer.class, String.class, javax.swing.ImageIcon.class,
                Integer.class, Integer.class, Double.class, String.class, String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types[columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return false;
            }

        });
        jTable1.setMaximumSize(new java.awt.Dimension(1214, 673));
        jTable1.setMinimumSize(new java.awt.Dimension(1214, 673));
        jScrollPane1.setViewportView(jTable1);

        jTabbedPane2.addTab("Sản phẩm", jScrollPane1);

        jTabbedPane1.addTab("Danh sách", jTabbedPane2);

        jTabbedPane3.setPreferredSize(new java.awt.Dimension(1214, 673));

        jLabelmasp.setText("Mã sản phẩm");

        jLabelloaisp.setText("Loại sản phẩm");

        jLabeltensp.setText("Tên sản phẩm");

        jLabelspluongsanpham.setText("Số lượng sản phẩm");

        jLabeldonvisp.setText("Đơn vị sản phẩm");

        jLabelgiabansp.setText("Giá bán sản phẩm");

        jLabeltrangthaisp.setText("Trạng thái sản phẩm");

        jTextFieldmasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldmaspActionPerformed(evt);
            }
        });

        jTextFieldtensp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtenspActionPerformed(evt);
            }
        });

        jLabelanh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelanh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelanhMouseClicked(evt);
            }
        });

        jButtoncapnhap.setText("Cập nhập");
        jButtoncapnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncapnhapActionPerformed(evt);
            }
        });

        jButtonlammoi.setText("Làm mới");
        jButtonlammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonlammoiActionPerformed(evt);
            }
        });

        jComboBox1.addItem("");
        jComboBox1.addItem("Áo thun");
        jComboBox1.addItem("Áo sơ mi");
        jComboBox1.addItem("Quần jean");
        jComboBox1.addItem("Váy đầm");
        jComboBox1.addItem("Áo khoác");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabeldonvisp, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelspluongsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabeltensp, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelloaisp, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelmasp, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(207, 207, 207))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabelgiabansp, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(180, 180, 180))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabeltrangthaisp, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(172, 172, 172)))))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldgiabansp, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldtrangthaisp, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(638, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextFielddonvisp, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178)
                        .addComponent(jButtoncapnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonlammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldmasp, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(jTextFieldsoluongsp, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(jTextFieldtensp, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelanh, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(160, 160, 160))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelmasp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldmasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeltensp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldtensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelloaisp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelspluongsanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldsoluongsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabelanh, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeldonvisp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFielddonvisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtoncapnhap, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonlammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelgiabansp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldgiabansp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabeltrangthaisp, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldtrangthaisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("tab1", jPanel4);

        jTabbedPane1.addTab("Chi tiết", jTabbedPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldtenspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtenspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldtenspActionPerformed

    private void jButtoncapnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncapnhapActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jButtoncapnhapActionPerformed

    private void jButtonlammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonlammoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonlammoiActionPerformed

    private void jLabelanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelanhMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelanhMouseClicked

    private void jButtontaosanphammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontaosanphammoiActionPerformed
   
    }//GEN-LAST:event_jButtontaosanphammoiActionPerformed

    private void jButtontimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontimActionPerformed
        // TODO add your handling code here:
    


    

    }//GEN-LAST:event_jButtontimActionPerformed

    private void jTextFieldmaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldmaspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldmaspActionPerformed

    private void jTextFieldnhaptenmaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnhaptenmaspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnhaptenmaspActionPerformed

    private void jButtonHuytimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHuytimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonHuytimActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed


    
    
   public void showSanPhamList(List<SanPhamModel> list) {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0); // Xóa dữ liệu cũ

    for (SanPhamModel sp : list) {
        // 1. Load ảnh từ thư mục "images/"
        ImageIcon icon = new ImageIcon("images/" + sp.getHinhAnh());
        // 2. Resize ảnh cho vừa ô bảng (60–80px)
        Image img = icon.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH);
        ImageIcon scaledIcon = new ImageIcon(img);

        // 3. Thêm dòng mới, với 9 cột: [Ma, Tên, Ảnh, TênLoại, SL, Giá, Đơn vị, Trạng thái, FileName]
        model.addRow(new Object[]{
            sp.getMaSanPham(),
            sp.getTenSanPham(),
            scaledIcon,
            sp.getTenLoaiSanPham(),    // hiển thị tên loại
            sp.getSoLuong(),
            sp.getGiaSanPham(),
            sp.getDonVi(),
            sp.getTrangThai(),
            sp.getHinhAnh()            // ẩn cột này sau
        });
    }

    // Ẩn cột "Tên file ảnh" (cột index 8)
    if (jTable1.getColumnCount() > 8) {
        jTable1.getColumnModel().getColumn(8).setMinWidth(0);
        jTable1.getColumnModel().getColumn(8).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(8).setPreferredWidth(0);
    }




}

    

  
    

   
    private QuanLySanPhamController controller;

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonHuytim;
    public javax.swing.JButton jButtoncapnhap;
    public javax.swing.JButton jButtonlammoi;
    public javax.swing.JButton jButtontaosanphammoi;
    public javax.swing.JButton jButtontim;
    public javax.swing.JButton jButtonxuatexcel;
    public javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabelanh;
    private javax.swing.JLabel jLabeldonvisp;
    private javax.swing.JLabel jLabelgiabansp;
    private javax.swing.JLabel jLabelloaisp;
    private javax.swing.JLabel jLabelmasp;
    private javax.swing.JLabel jLabelspluongsanpham;
    private javax.swing.JLabel jLabeltensp;
    public javax.swing.JLabel jLabelthongbaotim;
    private javax.swing.JLabel jLabeltrangthaisp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    public javax.swing.JTable jTable1;
    public javax.swing.JTextField jTextFielddonvisp;
    public javax.swing.JTextField jTextFieldgiabansp;
    public javax.swing.JTextField jTextFieldmasp;
    public javax.swing.JTextField jTextFieldnhaptenmasp;
    public javax.swing.JTextField jTextFieldsoluongsp;
    public javax.swing.JTextField jTextFieldtensp;
    public javax.swing.JTextField jTextFieldtrangthaisp;
    // End of variables declaration//GEN-END:variables
}
