package view;

import controller.QuanLySanPhamController;
import controller.TaoSanPhamController;
import java.awt.Image;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lenovo
 */
public class Taosanphammoi extends javax.swing.JFrame {

     public QuanLySanPhamController parentController;
    private TaoSanPhamController controller;
    public String selectedImageFileName = "";
    /**
     * Creates new form Taosanphammoi
     */
    public Taosanphammoi(QuanLySanPhamController parentController) {
        initComponents();
        this.parentController = parentController;
        controller = new TaoSanPhamController(this);
        controller.loadLoaiSanPham();
         selectedImageFileName = "default.jpg";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldmasp = new javax.swing.JTextField();
        jTextFieldtensp = new javax.swing.JTextField();
        jTextFieldgiasp = new javax.swing.JTextField();
        jLabelChonHinhanh = new javax.swing.JLabel();
        jButtonTao = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldsoluongsp = new javax.swing.JTextField();
        jLabelDonvi = new javax.swing.JLabel();
        jTextFieldDonvi = new javax.swing.JTextField();
        jComboBoxtaosanphammoi = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setForeground(new java.awt.Color(34, 47, 62));
        jLabel1.setText("Tạo sản phẩm mới");

        jLabel2.setForeground(new java.awt.Color(34, 47, 62));
        jLabel2.setText("Mã sản phẩm");

        jLabel3.setForeground(new java.awt.Color(34, 47, 62));
        jLabel3.setText("Tên sản phẩm");

        jLabel4.setForeground(new java.awt.Color(34, 47, 62));
        jLabel4.setText("Loại sản phẩm");

        jLabel5.setForeground(new java.awt.Color(34, 47, 62));
        jLabel5.setText("Giá sản phẩm");
        jLabel5.setToolTipText("");

        jTextFieldmasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldmaspActionPerformed(evt);
            }
        });

        jLabelChonHinhanh.setForeground(new java.awt.Color(34, 47, 62));
        jLabelChonHinhanh.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelChonHinhanh.setText("Click vào để chọn hình ảnh");
        jLabelChonHinhanh.setToolTipText("");
        jLabelChonHinhanh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelChonHinhanh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelChonHinhanhMouseClicked(evt);
            }
        });

        jButtonTao.setBackground(new java.awt.Color(34, 47, 62));
        jButtonTao.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTao.setText("Tạo");
        jButtonTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaoActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(34, 47, 62));
        jLabel8.setText("Số lượng");

        jLabelDonvi.setForeground(new java.awt.Color(34, 47, 62));
        jLabelDonvi.setText("Đơn vị");

        jComboBoxtaosanphammoi.addItem("");
        jComboBoxtaosanphammoi.addItem("Áo thun");
        jComboBoxtaosanphammoi.addItem("Áo sơ mi");
        jComboBoxtaosanphammoi.addItem("Quần jean");
        jComboBoxtaosanphammoi.addItem("Váy đầm");
        jComboBoxtaosanphammoi.addItem("Áo khoác");
        jComboBoxtaosanphammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxtaosanphammoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonTao, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(301, 301, 301))
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(86, 86, 86)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDonvi, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldDonvi, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                        .addGap(490, 490, 490))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldgiasp, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                            .addComponent(jTextFieldsoluongsp)
                            .addComponent(jTextFieldmasp)
                            .addComponent(jTextFieldtensp)
                            .addComponent(jComboBoxtaosanphammoi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelChonHinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldmasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldtensp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxtaosanphammoi)
                                .addGap(3, 3, 3)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldgiasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldsoluongsp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelChonHinhanh, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDonvi, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldDonvi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(jButtonTao)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaoActionPerformed
        // TODO add your handling code here:
         controller.createSanPham();
    }//GEN-LAST:event_jButtonTaoActionPerformed

    private void jLabelChonHinhanhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelChonHinhanhMouseClicked
        JFileChooser filechooser = new JFileChooser();
    filechooser.setDialogTitle("Chọn hình ảnh");
    filechooser.setFileFilter(new FileNameExtensionFilter("Hình ảnh", "jpg", "jpeg", "png"));

    int result = filechooser.showOpenDialog(this);
    if (result == JFileChooser.APPROVE_OPTION) {
        java.io.File selectedFile = filechooser.getSelectedFile();

        // 1) Cập nhật tên file để khi tạo dùng đúng
        selectedImageFileName = selectedFile.getName();

        // 2) Copy file vào thư mục images/ (tạo folder images cạnh src nếu chưa có)
        try {
            java.nio.file.Files.copy(
                selectedFile.toPath(),
                java.nio.file.Paths.get("images", selectedImageFileName),
                java.nio.file.StandardCopyOption.REPLACE_EXISTING
            );
        } catch (java.io.IOException ex) {
            ex.printStackTrace();
        }

        // 3) Load ảnh từ thư mục images/ và scale
        String loadPath = "images/" + selectedImageFileName;
        ImageIcon icon = new ImageIcon(loadPath);
        Image img = icon.getImage().getScaledInstance(
            jLabelChonHinhanh.getWidth(),
            jLabelChonHinhanh.getHeight(),
            Image.SCALE_SMOOTH
        );
        jLabelChonHinhanh.setIcon(new ImageIcon(img));
        jLabelChonHinhanh.setText("");
    }


    }//GEN-LAST:event_jLabelChonHinhanhMouseClicked

    private void jComboBoxtaosanphammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxtaosanphammoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxtaosanphammoiActionPerformed

    private void jTextFieldmaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldmaspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldmaspActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Taosanphammoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Taosanphammoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Taosanphammoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Taosanphammoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Taosanphammoi(null).setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonTao;
    public javax.swing.JComboBox<String> jComboBoxtaosanphammoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    public javax.swing.JLabel jLabelChonHinhanh;
    private javax.swing.JLabel jLabelDonvi;
    public javax.swing.JTextField jTextFieldDonvi;
    public javax.swing.JTextField jTextFieldgiasp;
    public javax.swing.JTextField jTextFieldmasp;
    public javax.swing.JTextField jTextFieldsoluongsp;
    public javax.swing.JTextField jTextFieldtensp;
    // End of variables declaration//GEN-END:variables
}
